apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: python-blockchain-tutorial
build:
  artifacts:
    - image: backend
      context: .
      docker:
        dockerfile: backend/Dockerfile

    - image: frontend
      context: .
      docker:
        dockerfile: frontend/Dockerfile
manifests:
  rawYaml:
    - k8s/*.yml
